### ISSUE TITLE
API Keys management via interface

### ISSUE THREAD

**Issue by albertmeronyo** [CLARIAH/wp4-requirements#27]

**Comment by RinkeHoekstra** [comment]
Problem: how to retract API keys (esp. with JSON web tokens, because there is no session store)

Possible solution:
- Make sure that API keys do as little as possible (one API key per type of access/function)
- Blacklisting web tokens is tricky (read up on this)

In general: how can we manage them (creating them is easy)

**Comment by LaurensRietveld** [comment]
This is resolved now. The API key interface is finished, andt etracting works. The blacklisting works as well, but propagation of a new blacklisted tokens might have a delay of up to 5 minutes (due to some optimization I wanted to perform)

**Comment by RinkeHoekstra** [comment]
Question: where is it, and how can we use it?
