### ISSUE TITLE
Inspector provenance query does not return label for persons

### ISSUE THREAD

**Issue by RinkeHoekstra** [CLARIAH/wp4-requirements#39]

**Comment by RinkeHoekstra** [comment]
Turns out that some user identifiers, i.e. emails, are percent-encoded (@ vs %40). This causes a disconnection between datasets and the actual user.

**Comment by albertmeronyo** [comment]
The namespaces.yaml file had an incorrect FOAF namespace URI, which caused the issue. All CSVW-based conversions were affected. This is now fixed, and the server is (or should be) working to put new versions online.

Another fix: the queries are now adapted in such a way that the ClioInfra datasets are visualised as one big cluster rather than a large number of disconnected nodes.
